### Stroke Prediction Dataset - Acidente Vascular Cerebral
* https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset

*  Stroke is a medical emergency. A stroke occurs when blood flow to a part of your brain is interrupted or reduced, preventing brain tissue from getting oxygen and nutrients. Brain cells begin to die within minutes

* Age: People aged 55 years and over

* Hypertension: if the systolic pressure is 140 mm Hg or more, or the diastolic pressure is 90 mm Hg or more

* Hypercholesterolemia: If the cholesterol level in the blood is 200 milligrams per deciliter

* Smoking

* Diabetes

* Obesity: if the body mass index (BMI) is 30 or more

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
# Carrega a base de dados
df=pd.read_csv('healthcare-dataset-stroke-data.csv')
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

### Limpeza e Normalização

In [3]:
# formato dos dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   str
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   str
 6   work_type          5110 non-null   str
 7   Residence_type     5110 non-null   str
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   str
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), str(5)
memory usage: 479.2 KB

Limpeza do atributo BMI

In [4]:
media = df['bmi'].mean()
media

np.float64(28.893236911794666)

In [5]:
df['bmi'] = df['bmi'].fillna(media)

In [6]:
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   str
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   str
 6   work_type          5110 non-null   str
 7   Residence_type     5110 non-null   str
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                5110 non-null   float64
 10  smoking_status     5110 non-null   str
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), str(5)
memory usage: 479.2 KB

Normalização com StandardScaler()

In [8]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='str')

In [9]:
columns = ['age','avg_glucose_level','bmi']

In [10]:
scaler = StandardScaler()

In [11]:
ajuste = scaler.fit(df[columns])
df[columns] = ajuste.transform(df[columns])

In [12]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,1.051434,0,1,Yes,Private,Urban,2.706375,1.001234e+00,formerly smoked,1
1,51676,Female,0.786070,0,0,Yes,Self-employed,Rural,2.121559,4.615554e-16,never smoked,1
2,31112,Male,1.626390,0,1,Yes,Private,Rural,-0.005028,4.685773e-01,never smoked,1
3,60182,Female,0.255342,0,0,Yes,Private,Urban,1.437358,7.154182e-01,smokes,1
4,1665,Female,1.582163,1,0,Yes,Self-employed,Rural,1.501184,-6.357112e-01,never smoked,1

In [13]:
# classe
df['stroke'].unique()

array([1, 0])

In [14]:
df['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

#### Transformação dos atributos categóricos
* OneHotEncoder aplicado em todos os atributos

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
categorical_columns = df.select_dtypes(include=['object']).columns.tolist()

C:\Users\willi\AppData\Local\Temp\ipykernel_9872\718535353.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns.tolist()

In [17]:
categorical_columns

['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

In [ ]:
# Gerar o objeto OneHotEncoder
encoder = OneHotEncoder()

# Transforma todos os atributos categóricos
one_hot_encoded = encoder.fit_transform(df[categorical_columns])

In [ ]:
# Deve transformar a matriz esparsa em um DataFrame. Atentar a informação "Sparse Row sparse matrix of dtype 'float64'"
one_hot_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 25550 stored elements and shape (5110, 16)>

In [20]:
one_hot_encoded.toarray()

array([[0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], shape=(5110, 16))

In [21]:
# Transformar os dados em um formato dataframe
one_hot_df = pd.DataFrame(one_hot_encoded.toarray(), columns = encoder.get_feature_names_out(categorical_columns) )

In [22]:
one_hot_df

,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5106,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5107,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5108,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5109,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [23]:
# Adicionar as novas colunas no Dataframe Original
df = pd.concat([df, one_hot_df], axis = 1)

In [24]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke', 'gender_Female', 'gender_Male',
       'gender_Other', 'ever_married_No', 'ever_married_Yes',
       'work_type_Govt_job', 'work_type_Never_worked', 'work_type_Private',
       'work_type_Self-employed', 'work_type_children', 'Residence_type_Rural',
       'Residence_type_Urban', 'smoking_status_Unknown',
       'smoking_status_formerly smoked', 'smoking_status_never smoked',
       'smoking_status_smokes'],
      dtype='str')

In [25]:
# Remove as colunas categóricas originais
df = df.drop(categorical_columns, axis = 1)

In [26]:
df.columns

Index(['id', 'age', 'hypertension', 'heart_disease', 'avg_glucose_level',
       'bmi', 'stroke', 'gender_Female', 'gender_Male', 'gender_Other',
       'ever_married_No', 'ever_married_Yes', 'work_type_Govt_job',
       'work_type_Never_worked', 'work_type_Private',
       'work_type_Self-employed', 'work_type_children', 'Residence_type_Rural',
       'Residence_type_Urban', 'smoking_status_Unknown',
       'smoking_status_formerly smoked', 'smoking_status_never smoked',
       'smoking_status_smokes'],
      dtype='str')

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              5110 non-null   int64
 1   age                             5110 non-null   float64
 2   hypertension                    5110 non-null   int64
 3   heart_disease                   5110 non-null   int64
 4   avg_glucose_level               5110 non-null   float64
 5   bmi                             5110 non-null   float64
 6   stroke                          5110 non-null   int64
 7   gender_Female                   5110 non-null   float64
 8   gender_Male                     5110 non-null   float64
 9   gender_Other                    5110 non-null   float64
 10  ever_married_No                 5110 non-null   float64
 11  ever_married_Yes                5110 non-null   float64
 12  work_type_Govt_job              5110 non-null   float64
 13  work_type_Never_worked          5110 non-null   float64
 14  work_type_Private               5110 non-null   float64
 15  work_type_Self-employed         5110 non-null   float64
 16  work_type_children              5110 non-null   float64
 17  Residence_type_Rural            5110 non-null   float64
 18  Residence_type_Urban            5110 non-null   float64
 19  smoking_status_Unknown          5110 non-null   float64
 20  smoking_status_formerly smoked  5110 non-null   float64
 21  smoking_status_never smoked     5110 non-null   float64
 22  smoking_status_smokes           5110 non-null   float64
dtypes: float64(19), int64(4)
memory usage: 918.3 KB

In [28]:
df.shape

(5110, 23)

### Amostragem

Houldout e Balanceamento das classes
* Separação entre treino e teste (70% e 30%)

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [30]:
# Separar os atributos e a classe
X = df.drop(['stroke'], axis=1)
y = df['stroke']

In [31]:
X.shape, df.shape

((5110, 22), (5110, 23))

In [32]:
# Amostragem por houldout
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [33]:
X_train.shape, X_test.shape

((3577, 22), (1533, 22))

In [34]:
DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)
y_pred = DT.predict(X_test)

In [35]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96      1450
           1       0.17      0.14      0.16        83

    accuracy                           0.92      1533
   macro avg       0.56      0.55      0.56      1533
weighted avg       0.91      0.92      0.91      1533

In [36]:
confusion_matrix(y_test,y_pred)

array([[1391,   59],
       [  71,   12]])

In [37]:
y_test.value_counts()

stroke
0    1450
1      83
Name: count, dtype: int64

Balanceamento das classes
* https://medium.com/analytics-vidhya/undersampling-and-oversampling-an-old-and-a-new-approach-4f984a0e8392
* Abordagem SMOTE

In [38]:
df['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [39]:
from imblearn.over_sampling import SMOTE

In [40]:
sm = SMOTE()
X_balanced, y_balanced = sm.fit_resample(X, y)

In [41]:
X_balanced.shape

(9722, 22)

In [42]:
y_balanced.value_counts()

stroke
1    4861
0    4861
Name: count, dtype: int64

In [46]:
X_train,X_test,y_train, y_test = train_test_split(X_balanced, y_balanced, test_size=0.2)

In [47]:
X_train.shape, X_test.shape

((7777, 22), (1945, 22))

In [48]:
y_train.value_counts(), y_test.value_counts()

(stroke
 0    3897
 1    3880
 Name: count, dtype: int64,
 stroke
 1    981
 0    964
 Name: count, dtype: int64)

In [49]:
DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)
y_pred = DT.predict(X_test)

In [50]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93       964
           1       0.93      0.94      0.93       981

    accuracy                           0.93      1945
   macro avg       0.93      0.93      0.93      1945
weighted avg       0.93      0.93      0.93      1945

In [51]:
confusion_matrix(y_test,y_pred)

array([[897,  67],
       [ 62, 919]])

## Validação Cruzada

In [52]:
from sklearn.metrics import accuracy_score

from sklearn.model_selection import (
    KFold,
    LeaveOneOut,
    StratifiedKFold,
    cross_validate
)

### K-fold Cross-validation

In [53]:
DT = DecisionTreeClassifier()
# K-Fold Cross-Validation
kf = KFold(n_splits=10, shuffle=True)

# estimate generalization error
clf =  cross_validate(
    DT,
    X,
    y,
    scoring='balanced_accuracy',
    return_train_score=True,
    cv=kf, # k-fold
)

print(f"{clf['test_score']}\nMédia: {np.mean(clf['test_score'])}")

[0.54522752 0.52869605 0.54165182 0.59064235 0.57427984 0.55899256
 0.56991952 0.62016129 0.57633745 0.58239492]
Média: 0.5688303319853849

Balanceado

In [54]:
DT = DecisionTreeClassifier()
# K-Fold Cross-Validation
kf = KFold(n_splits=10, shuffle=True)

# estimate generalization error
clf =  cross_validate(
    DT,
    X_balanced,
    y_balanced,
    scoring='balanced_accuracy',
    return_train_score=True,
    cv=kf, # k-fold
)

print(f"{clf['test_score']}\nMédia: {np.mean(clf['test_score'])}")

[0.93074329 0.93943409 0.95004921 0.9472991  0.93234021 0.9453129
 0.94145373 0.94299803 0.94116638 0.95267943]
Média: 0.942347637259242

### Stratified K-fold Cross-validation

In [55]:
DT = DecisionTreeClassifier()
# Stratified Cross-Validation
skf = StratifiedKFold(n_splits=10, shuffle=True)

# estimate generalization error
clf =  cross_validate(
    DT,
    X,
    y,
    scoring='balanced_accuracy',
    return_train_score=True,
    cv=skf, # k-fold
)

print(f"{clf['test_score']}\nMédia: {np.mean(clf['test_score'])}")

[0.568107   0.53325103 0.53736626 0.63736626 0.49633745 0.55736626
 0.55530864 0.63427984 0.60148148 0.58260609]
Média: 0.5703470289248865

Balanceado

In [56]:
DT = DecisionTreeClassifier()
# Stratified Cross-Validation
skf = StratifiedKFold(n_splits=10, shuffle=True)

# estimate generalization error
clf =  cross_validate(
    DT,
    X_balanced,
    y_balanced,
    scoring='balanced_accuracy',
    return_train_score=True,
    cv=skf, # k-fold
)

print(f"{clf['test_score']}\nMédia: {np.mean(clf['test_score'])}")

[0.9373104  0.94860192 0.94341564 0.94135802 0.94855967 0.94341564
 0.93312757 0.95473251 0.9537037  0.94238683]
Média: 0.9446611909650926